sudo: required

language: python

services:
      - docker

before_install:
      - curl -L https://github.com/docker/compose/releases/download/1.7.0/docker-compose-`uname -s`-`uname -m` > docker-compose
      - chmod +x docker-compose
      - sudo mv docker-compose /usr/local/bin
      - docker-compose version

script:
      - LOCAL_TAG=`cat tag.txt`
      - if [ "$LOCAL_TAG" == ""  ]; then LOCAL_TAG=postgres; fi
      - echo $LOCAL_TAG
      - ./init $LOCAL_TAG
      - docker-compose build
      - docker-compose up -d
      - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - VERSION=`cat version.txt`
      - if [ "$VERSION" == ""  ]; then VERSION=latest; fi

      - MYTARDIS_IMG_REPO=$DOCKER_USERNAME/mytardis-app-"$LOCAL_TAG":"$VERSION"-travis
      - NGINX_IMG_REPO=$DOCKER_USERNAME/mytardis-nginx-"$LOCAL_TAG":"$VERSION"-travis
      - docker commit -a "$DOCKER_AUTHOR" -m "auto build" dockermytardis_app_1 $MYTARDIS_IMG_REPO
      - docker commit -a "$DOCKER_AUTHOR" -m "auto build" dockermytardis_nginx_1 $NGINX_IMG_REPO
      - docker push $MYTARDIS_IMG_REPO
      - docker push $NGINX_IMG_REPO
