sudo: required

language: python

services: 
	- docker

before_install:
	- curl -L https://github.com/docker/compose/releases/download/1.4.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
	- chmod +x /usr/local/bin/docker-compose
	
