version: "2"

services:

  test:
    restart: "no"
    build: mytardis-test
    volumes:
      - ./data:/data
    env_file: ".env"
    networks:
      - mytardis

networks:
    mytardis:
      external:
        name: dockermytardis_mytardis
    
